manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: od
      url-base: https://github.com/olidacombe
    - name: void
      url-base: https://github.com/victorlucachi
  projects:
    - name: zmk
      remote: od
      revision: void_pmw3610-aml
      import: app/west.yml
  self:
    path: config
